{% set data = load_setup_py_data() %}

package:
  name: stylegan2_torch
  version: {{ data["version"] }}

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python

requirements:
  host:
    - python
    - pip
    - dunamai
  run:
    - python
    {% for dep in data["install_requires"] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest

about:
  home: {{ data["url"] }}
  summary: {{ data["description"] }}
  description: {{ data["description"] }}
  license: {{ data["license"] }}
  license_file: LICENSE
  dev_url: {{ data["url"] }}
  doc_url: https://ppeetteerrs.github.io/stylegan2_torch